name: Build Release for Windows

on:
  push:
    tags:
      - 'v*' # Сборка запустится автоматически, когда вы создадите тег версии (например, v1.0)

jobs:
  build:
    runs-on: windows-latest # GitHub запустит чистую Windows-машину

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build --config Release

    - name: Create Release and Upload Artifact
      uses: softprops/action-gh-release@v2
      with:
        files: build/Release/*.exe # Путь к вашему готовому файлу после компиляции
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
