name: Build Release for Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build Project
      shell: bash
      env:
        MSYS_NO_PATHCONV: 1
      run: |
        # Ищем все файлы с расширением .cpp во всех папках проекта
        CPP_FILES=$(find . -name "*.cpp" | tr '\n' ' ')
        echo "Найдено файлов для сборки: $CPP_FILES"
        
        # Компилируем без -EHsc, добавляем сборку графической подсистемы Windows
        cl.exe -clr -O2 $CPP_FILES -Fe:graphic_calc.exe -link -subsystem:windows

    - name: Create Release and Upload Artifact
      uses: softprops/action-gh-release@v2
      with:
        files: graphic_calc.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
